version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - "5000"
    volumes:
      - "/c/code/node/ArduinoObstgarten/frontend/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/c/code/tmp/redis/data:/data:rw"
      - "/c/code/tmp/redis/var:/var/redis:rw"
    restart: always
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf

  frontend:
    image: atopi/arduino_obstgarten:latest
    ports:
      - "80:3000"
      - "3030"
    depends_on: redis
    container_name: frontend
    depends_on:
      - "redis"
