FROM node:lts-alpine

WORKDIR /dist

COPY ArduinoObstgarten/* ./ArduinoObstgarten/
COPY Login/* ./Login/
COPY Server/* ./Server/

RUN cd /dist/Server && npm install
RUN cd /dist/Login && npm install
RUN cd /dist/ArduinoObstgarten && npm install

EXPOSE 3000
EXPOSE 3030

CMD [ "node", "./Server/server.js" ]
