---
- hosts: gateways
  tasks:
    - name: Register node value
      shell: cat /etc/node
      register: node
      ignore_errors: true

    - name: Install aptitude
      become: true
      package:
        name: aptitude
        state: present

    - name: Upgrade all packages
      become: true
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install batctl
      become: true
      package:
        name: batctl
        state: present

    - name: Install alfred
      become: true
      package:
        name: alfred
        state: present

    - name: Install iw
      become: true
      package:
        name: iw
        state: present

    - name: Install iproute2
      become: true
      package:
        name: iproute2
        state: present

    - name: Place batman-adv in /etc/modules
      become: true
      lineinfile:
        path: /etc/modules
        line: batman-adv

    - name: Set startup to rc.local
      become: true
      lineinfile:
        dest: /etc/rc.local
        line: "{{ item.line }}"
        insertafter: "{{ item.after }}"
        state: present
      with_items: 
        - { line: "batctl if add wlan0", after: "^fi" }
        - { line: "ifconfig wlan0 up", after: "^batctl if add wlan0" }
        - { line: "ifconfig bat0 up", after: "^ifconfig wlan0 up" }
        - { line: "ifconfig bat0 192.168.111.{{ node.stdout }}", after: "^ifconfig bat0 up" }
        - { line: "batctl gw server", after: "^ifconfig bat0 192.168.111.{{ node.stdout }}" }
        - { line: "iptables-restore < /etc/iptables.ipv4.nat", after: "^batctl gw server" }

    - name: Set nameserver to 8.8.8.8
      become: true
      lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver 8.8.8.8"

    - name: Copy wlan0
      become: true
      copy:
        src: wlan0
        dest: /etc/network/interfaces.d

    - name: Copy bat0
      become: true
      copy:
        src: bat0
        dest: /etc/network/interfaces.d

    - name: Load batman-adv to kernel
      become: true
      modprobe:
        name: batman-adv
        state: present

    - name: Stop dhcpd from using wlan0
      become: true
      lineinfile:
        path: /etc/dhcpcd.conf
        line: denyinterfaces wlan0

    - name: Enable ipv4 forwarding in /etc/sysctl.conf
      become: true
      lineinfile:
        dest: /etc/sysctl.conf
        line: "net.ipv4.ip_forward=1"

    - name: Add a masquerade for outbound traffic on eth0
      become: true
      shell: "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"

    - name: Save the iptables roule for restore in rc.local
      become: true
      shell: "sh -c 'iptables-save > /etc/iptables.ipv4.nat'"

