---
- hosts: nodes
  tasks:
    - name: Register node value
      shell: cat /etc/node
      register: node
      ignore_errors: true

    - name: Install aptitude
      become: true
      package:
        name: aptitude
        state: present

    - name: Upgrade all packages
      become: true
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install batctl
      become: true
      package:
        name: batctl
        state: present

    - name: Install alfred
      become: true
      package:
        name: alfred
        state: present

    - name: Install iw
      become: true
      package:
        name: iw
        state: present

    - name: Install iproute2
      become: true
      package:
        name: iproute2
        state: present

    - name: Install git
      become: true
      package:
        name: git
        state: present
  
    - name: Install python3
      become: true
      package:
        name: python3
        state: present

    - name: Install pip
      become: true
      package:
        name: python3-pip
        state: present

    - name: Place batman-adv in /etc/modules
      become: true
      lineinfile:
        path: /etc/modules
        line: batman-adv

    - name: Set startup to rc.local
      become: true
      lineinfile:
        dest: /etc/rc.local
        line: "{{ item.line }}"
        insertafter: "{{ item.after }}"
        state: present
      with_items: 
        - { line: "batctl if add wlan0", after: "^fi" }
        - { line: "ifconfig wlan0 up", after: "^batctl if add wlan0" }
        - { line: "ifconfig bat0 up", after: "^ifconfig wlan0 up" }
        - { line: "ifconfig bat0 192.168.111.{{ node.stdout }}", after: "^ifconfig bat0 up" }
        - { line: "batctl gw client", after: "^ifconfig bat0 192.168.111.{{ node.stdout }}" }
        - { line: "route add default gw 192.168.111.10 bat0", after: "^batctl gw client" }
        - { line: "nohup python3 /home/pi/ArduinoObstgarten/serial_read.py </dev/null >>/home/pi/script-output.log 2>&1 &", after: "^route add default gw 192.168.111.10 bat0"}

    - name: Set nameserver to 8.8.8.8
      become: true
      lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver 8.8.8.8"

    - name: Copy wlan0
      become: true
      copy:
        src: wlan0
        dest: /etc/network/interfaces.d

    - name: Copy bat0
      become: true
      copy:
        src: bat0
        dest: /etc/network/interfaces.d

    - name: Load batman-adv to kernel
      become: true
      modprobe:
        name: batman-adv
        state: present

    - name: Stop dhcpd from using wlan0
      become: true
      lineinfile:
        dest: /etc/dhcpcd.conf
        line: denyinterfaces wlan0

    - name: Stop dhcpd from using bat0
      become: true
      lineinfile:
        dest: /etc/dhcpcd.conf
        line: denyinterfaces bat0


    - name: Install serial program on node
      git:
        repo: https://github.com/atopion/ArduinoObstgarten.git
        dest: /home/pi/ArduinoObstgarten

    - name: Install repository dependencies
      pip:
        name:
          - serial
          - requests
      ignore_errors: true

    - name: Start python script
      become: true
      shell: nohup python3 /home/pi/ArduinoObstgarten/serial_read.py </dev/null >>/home/pi/script-output.log 2>&1 &
